language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"

script:
    - cd test
    - ln -s ../Makefile .
    - make
    - make sdist
    - make bdist
    - make check
    - make clean

branches:
  only:
    - master
